remote_theme: pages-themes/cayman@v0.2.0
plugins:
  - jekyll-remote-theme

title: Welcome to the Kdautoml.jl, a knowledge-driven AutoML library!
description: Principles, usage and useful things to know about Kdautoml.jl
